title = 'Julien Wittouck'
theme = "poison"

defaultContentLanguage = 'fr'

baseUrl = 'https://codeka.io'

[languages]
  [languages.fr]
    languageCode = 'fr-FR'
    languageName = 'FranÃ§ais'
  [languages.en]
    languageCode = 'en'
    languageName = 'English'

[taxonomies]
  series = 'series'
  tags   = 'tags'

[permalinks]
  [permalinks.page]
    posts = '/:year/:month/:day/:slug'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.link]
        useEmbedded = 'always'
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[outputs]
  home = ['html', 'rss']

[params]
  brand = "Julien Wittouck"
  author_name = "Julien Wittouck"
  brand_image = 'pp_ekite_itvw.png'
  og_image = 'pp_ekite_itvw.png'
  description = "freelance solution & software architect ğŸ— - containers ğŸ‹ & linux ğŸ§ â¤ï¸ - teacher & trainer ğŸ“ @ univ-lille.fr - speaker ğŸ™ - Team @Cloud_Nord"
  front_page_content = ["posts", "projects", "books"]

  certifications = [
    {Name = "CKAD: Certified Kubernetes Application Developer", Issuer= "The Linux Foundation", Issued= "2023-12", Expires= "2026-12", Credentials= "https://www.credly.com/badges/cdd863d0-5136-44e1-a393-8fa2dd736fa2/public_url", Logo= "/credentials/ckad-certified-kubernetes-application-developer.png"},
    {Name = "HashiCorp Certified: Terraform Associate (003)", Issuer= "HashiCorp", Issued= "2023-11", Expires= "2025-11", Credentials= "https://www.credly.com/badges/c8e35084-2c3d-443f-96fd-76a46b237360/public_url", Logo= "/credentials/hashicorp-certified-terraform-associate-003.png"}
  ]

  plausible = true
  plausible_domain = "codeka.io"
  plausible_script = "https://plausible.io/js/script.js"

  menu = [
    {Name = "Posts", URL = "/posts/", HasChildren = true, Limit = 3},
    {Name = "Talks", URL = "/talks/", HasChildren = true, Limit = 3 },
    {Name = "Projects", URL = "/projects/", HasChildren = true, Limit = 3},
    {Name = "AI Manifesto", Page = "/ai/"},
    {Name = "now", Page = "/now/"},
    {Name = "stats", Page = "/stats/"}
  ]

  email_url = "mailto:julien.wittouck@gmail.com"
  github_url = "https://github.com/juwit"
  linkedin_url = "https://www.linkedin.com/in/julien-wittouck"
  twitter_url = "https://www.twitter.com/CodeKaio"
  bluesky_url = "https://bsky.app/profile/codeka.io"
  mastodon_url = "https://mas.to/@codekaio"
  rss_icon = true

  # Hex colors for your sidebar.
  moon_sun_background_color = "#515151"   # default is #515151
  moon_sun_color = "#FFF"                 # default is #FFF
  sidebar_a_color = "#FFF"                # default is #FFF
  sidebar_bg_color = "#5ea4e2"            # default is #202020
  sidebar_h1_color = "#FFF"               # default is #FFF
  sidebar_img_border_color = "#515151"    # default is #515151
  sidebar_p_color = "#111111"             # default is #909090
  sidebar_socials_color = "#FFF"          # default is #FFF

[privacy]
  [privacy.youTube]
    privacyEnhanced = true

[frontmatter]
  lastmod = ['lastmod', 'modified']